Run this code in google to reproduce our results!

In [1]:
!git clone https://github.com/sarahuston77/universal-adversarial-perturbations-facial-recognition.git
%cd universal-adversarial-perturbations-facial-recognition

fatal: destination path 'universal-adversarial-perturbations-facial-recognition' already exists and is not an empty directory.
/content/universal-adversarial-perturbations-facial-recognition


This may require restarting the juptyer notebook.

In [2]:
!pip install -r requirements.txt

In [10]:
!chmod +x setup_data.sh
!bash setup_data.sh

Streaming output truncated to the last 5000 lines.
  inflating: crop_part1/28_1_4_20170105164121996.jpg.chip.jpg  
  inflating: crop_part1/2_0_2_20161219162132342.jpg.chip.jpg  
  inflating: crop_part1/49_1_0_20170109142119876.jpg.chip.jpg  
  inflating: crop_part1/9_0_0_20170110220236260.jpg.chip.jpg  
  inflating: crop_part1/85_0_0_20170111205830721.jpg.chip.jpg  
  inflating: crop_part1/53_1_0_20170110160643329.jpg.chip.jpg  
  inflating: crop_part1/1_1_2_20161219195923075.jpg.chip.jpg  
  inflating: crop_part1/45_0_4_20170108230309811.jpg.chip.jpg  
  inflating: crop_part1/9_0_0_20170110220132059.jpg.chip.jpg  
  inflating: crop_part1/1_1_2_20161219203303165.jpg.chip.jpg  
  inflating: crop_part1/25_1_2_20170104022723237.jpg.chip.jpg  
  inflating: crop_part1/2_0_2_20161219140712432.jpg.chip.jpg  
  inflating: crop_part1/61_0_0_20170105173647189.jpg.chip.jpg  
  inflating: crop_part1/2_1_3_20161220222832003.jpg.chip.jpg  
  inflating: crop_part1/85_1_0_20170110183057797.jpg.chip.jp

Only run the split once; otherwise you will get errors.

In [11]:
!python3 split_data_test_train.py "data/crop_part1" "train_utk_dataset" "test_utk_dataset"

                                   filename  age  gender  race
0     10_0_0_20170110224253445.jpg.chip.jpg   10       0     0
1      1_0_3_20161219224645904.jpg.chip.jpg    1       0     3
2      1_0_2_20170109191453449.jpg.chip.jpg    1       0     2
3      2_0_3_20161220144926901.jpg.chip.jpg    2       0     3
4      8_1_0_20170109205515528.jpg.chip.jpg    8       1     0
...                                     ...  ...     ...   ...
9773  68_1_0_20170110155156093.jpg.chip.jpg   68       1     0
9774  69_0_1_20170111200716106.jpg.chip.jpg   69       0     1
9775   9_0_0_20170110225341709.jpg.chip.jpg    9       0     0
9776  29_1_2_20170104021825031.jpg.chip.jpg   29       1     2
9777  26_1_3_20170109134536902.jpg.chip.jpg   26       1     3

[9778 rows x 4 columns]
Train: 6844, Test: 2934

Sanity checks, the gender proportions for both train and test should be similar 
train:
gender
1    0.553039
0    0.446961
Name: proportion, dtype: float64

test:
gender
1    0.552488
0    0.447

In [ ]:
!python3 deepface_uap.py

I0000 00:00:1775844396.743790    9082 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Done importing...
Loading gender model from deepface...
W0000 00:00:1775844408.048234    9082 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
I0000 00:00:1775844408.055127    9082 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 7409 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1775844408.097605    9082 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
W0000 00:00:1775844408.179014    9082 c_api.cc:305] Operation '{name:'predictions/kernel/Assign' id:421 op devic

In [ ]:
import numpy as np
u_p = np.load("data/RACE.npy")
print(u_p.shape)
print(u_p)

(1, 224, 224, 3)
[[[[ 1.34531741e-03  1.42215932e-02 -1.63928014e-02]
   [-3.42139910e-03  1.19622669e-02  5.08947433e-03]
   [-6.87377091e-03  4.20252003e-03  7.22373812e-03]
   ...
   [ 1.08908319e-02  4.45154383e-03 -1.14268467e-02]
   [ 1.33767728e-02 -5.66001537e-03 -3.84606667e-03]
   [ 3.12421816e-02 -6.07187708e-03 -1.96630391e-02]]

  [[-2.25467032e-02 -8.63274270e-03 -2.32680336e-03]
   [ 7.43190944e-03 -2.59086824e-02  4.61034748e-03]
   [ 5.73901538e-03 -1.13655028e-02 -6.49040705e-03]
   ...
   [-3.42323197e-03 -6.08872599e-03 -1.56694134e-02]
   [ 4.19011467e-03  1.72018091e-02  1.17642587e-02]
   [ 5.09460836e-03 -2.79909521e-02 -1.53726179e-02]]

  [[-5.45379066e-04  1.66102806e-03 -1.11506186e-02]
   [ 2.05287988e-03 -8.55904689e-03  1.49862629e-02]
   [-1.16652449e-02  5.62820034e-03 -2.36372328e-02]
   ...
   [-3.70192032e-02 -9.24211483e-03  1.28181158e-02]
   [-1.54895074e-02 -1.68443334e-02 -9.08181233e-03]
   [ 3.74219616e-03 -2.08892361e-02  4.72392845e-03]]

  

In [ ]:
!python3 test_perturbations.py

I0000 00:00:1775856779.320318   62585 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Done importing...
Loading gender model from deepface...
W0000 00:00:1775856785.856146   62585 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
I0000 00:00:1775856785.858037   62585 gpu_device.cc:2043] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13757 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1775856785.873922   62585 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
W0000 00:00:1775856785.907115   62585 c_api.cc:305] Operation '{name:'conv2d_6/kernel/Assign' id:154 op device: