Run this code in google to reproduce our results!

In [2]:
!git clone https://github.com/sarahuston77/universal-adversarial-perturbations-facial-recognition.git
%cd universal-adversarial-perturbations-facial-recognition

fatal: destination path 'universal-adversarial-perturbations-facial-recognition' already exists and is not an empty directory.
/content/universal-adversarial-perturbations-facial-recognition


In [3]:
!pip install -r requirements.txt

In [23]:
!chmod +x setup_data.sh
!bash setup_data.sh

Streaming output truncated to the last 5000 lines.
  inflating: crop_part1/28_1_4_20170105164121996.jpg.chip.jpg  
  inflating: crop_part1/2_0_2_20161219162132342.jpg.chip.jpg  
  inflating: crop_part1/49_1_0_20170109142119876.jpg.chip.jpg  
  inflating: crop_part1/9_0_0_20170110220236260.jpg.chip.jpg  
  inflating: crop_part1/85_0_0_20170111205830721.jpg.chip.jpg  
  inflating: crop_part1/53_1_0_20170110160643329.jpg.chip.jpg  
  inflating: crop_part1/1_1_2_20161219195923075.jpg.chip.jpg  
  inflating: crop_part1/45_0_4_20170108230309811.jpg.chip.jpg  
  inflating: crop_part1/9_0_0_20170110220132059.jpg.chip.jpg  
  inflating: crop_part1/1_1_2_20161219203303165.jpg.chip.jpg  
  inflating: crop_part1/25_1_2_20170104022723237.jpg.chip.jpg  
  inflating: crop_part1/2_0_2_20161219140712432.jpg.chip.jpg  
  inflating: crop_part1/61_0_0_20170105173647189.jpg.chip.jpg  
  inflating: crop_part1/2_1_3_20161220222832003.jpg.chip.jpg  
  inflating: crop_part1/85_1_0_20170110183057797.jpg.chip.jp

In [ ]:
!python3 split_data_test_train.py

In [24]:
!python3 split_data_gender.py

Streaming output truncated to the last 5000 lines.
36_1_3_20170109141841866.jpg.chip.jpg
52_0_0_20170104212238236.jpg.chip.jpg
32_1_0_20170104165842857.jpg.chip.jpg
15_0_0_20170110232117349.jpg.chip.jpg
8_1_2_20170109203456419.jpg.chip.jpg
69_1_3_20170109150308256.jpg.chip.jpg
43_0_0_20170104210618508.jpg.chip.jpg
39_1_4_20170105173036253.jpg.chip.jpg
56_1_0_20170110152858178.jpg.chip.jpg
60_1_0_20170110131522551.jpg.chip.jpg
1_1_4_20161221193732358.jpg.chip.jpg
80_0_0_20170111200927317.jpg.chip.jpg
12_0_0_20170110224833703.jpg.chip.jpg
52_0_0_20170104212021653.jpg.chip.jpg
1_1_0_20170109191822349.jpg.chip.jpg
26_1_3_20170104222939159.jpg.chip.jpg
47_1_3_20170109133358794.jpg.chip.jpg
52_0_1_20170111171747356.jpg.chip.jpg
20_1_3_20170104231536521.jpg.chip.jpg
37_0_0_20170104185229157.jpg.chip.jpg
8_1_0_20170109202748999.jpg.chip.jpg
20_1_4_20170103223123528.jpg.chip.jpg
45_0_3_20170105163539339.jpg.chip.jpg
1_0_2_20161219211505437.jpg.chip.jpg
1_1_0_20170109193408973.jpg.chip.jpg
54_1_

In [ ]:
!python deepface_uap.py

Streaming output truncated to the last 5000 lines.
['8', '0', '0', '20170110215609467.jpg.chip.jpg']
['30', '0', '0', '20170104164938536.jpg.chip.jpg']
['7', '0', '0', '20170110215540131.jpg.chip.jpg']
['42', '0', '0', '20170105172350421.jpg.chip.jpg']
['65', '0', '3', '20170109143021566.jpg.chip.jpg']
['10', '0', '0', '20170110220251986.jpg.chip.jpg']
['1', '0', '2', '20161219161919870.jpg.chip.jpg']
['32', '0', '3', '20170104220341542.jpg.chip.jpg']
['39', '0', '0', '20170104181458853.jpg.chip.jpg']
['13', '0', '0', '20170103200856687.jpg.chip.jpg']
['49', '0', '0', '20170104213117085.jpg.chip.jpg']
['49', '0', '3', '20170109011146753.jpg.chip.jpg']
['1', '0', '2', '20161219211823957.jpg.chip.jpg']
['58', '0', '0', '20170109012156576.jpg.chip.jpg']
['3', '0', '2', '20161219162657782.jpg.chip.jpg']
['25', '0', '3', '20170104220223342.jpg.chip.jpg']
['10', '0', '0', '20170110224500062.jpg.chip.jpg']
['27', '0', '2', '20161219194038690.jpg.chip.jpg']
['65', '0', '0', '20170111201117758.

In [ ]:
import numpy as np
u_p = np.load("data/universal.npy")
print(u_p.shape)
print(u_p)

(1, 224, 224, 3)
[[[[-5.05660420e-01  1.33394628e-01  1.26115476e-01]
   [ 3.10409640e-02  9.13628875e-01  6.51642711e-01]
   [ 8.93770713e-01 -2.94826755e-01 -2.15215310e-01]
   ...
   [-1.30491980e+00  6.46602152e-05  6.82825828e-01]
   [ 3.64251126e-01 -3.94461080e-01  6.61434762e-01]
   [-1.18104712e-01 -9.46279478e-01 -1.02724572e+00]]

  [[ 6.99858109e-02  1.59998164e+00 -6.63912424e-01]
   [-6.22365440e-01  2.45081910e+00 -3.16395226e-01]
   [-1.00299091e+00 -2.75927456e-01 -1.80374870e+00]
   ...
   [ 8.09381342e-01  2.93480965e-01  3.77984352e-01]
   [ 1.04370499e+00  1.14996911e+00 -1.42791547e-01]
   [ 2.61588429e-01 -6.18714725e-01 -9.82702626e-01]]

  [[ 1.08329225e+00 -7.19846524e-02 -4.45850563e-02]
   [ 7.59520298e-01  5.80347258e-01  2.01032214e-01]
   [ 2.74145818e-01 -4.54617433e-01  1.83761737e-01]
   ...
   [-1.40633118e+00 -2.18495376e+00 -8.97016998e-01]
   [ 5.92437794e-01 -7.49670078e-01  1.77029136e+00]
   [-6.43199990e-01  1.87600630e-01 -1.01857200e+00]]

  

In [ ]:
!python3 test_perturbation.py

Done importing...
Loading gender model from deepface...
Dealing with graph mode...
Running session global variables intializer...
['16', '1', '0', '20170109214719630.jpg.chip.jpg']
['1', '0', '2', '20161219222527222.jpg.chip.jpg']
['36', '1', '0', '20170104171717858.jpg.chip.jpg']
['5', '1', '4', '20161223232211710.jpg.chip.jpg']
['2', '1', '3', '20161220144844310.jpg.chip.jpg']
['58', '0', '0', '20170104185324437.jpg.chip.jpg']
['49', '0', '3', '20170104220818198.jpg.chip.jpg']
['17', '1', '0', '20170109205309078.jpg.chip.jpg']
['29', '0', '4', '20170103235921692.jpg.chip.jpg']
['1', '0', '0', '20161219154018476.jpg.chip.jpg']
['15', '0', '0', '20170110223430616.jpg.chip.jpg']
['57', '0', '0', '20170104212600580.jpg.chip.jpg']
['2', '1', '4', '20161221202110987.jpg.chip.jpg']
['15', '0', '0', '20170110232306381.jpg.chip.jpg']
['4', '1', '4', '20161221200153784.jpg.chip.jpg']
['2', '1', '4', '20170103210934483.jpg.chip.jpg']
['39', '1', '0', '20170105001220803.jpg.chip.jpg']
['4', '0',